### ISSUE TITLE
Login screen flickers with every keystroke

### ISSUE THREAD

**Issue by techmaharaj** [paralus/dashboard#136]
#### Actual:
On the login page when keying in the email id and the password, the page flickers with every key stroke. Video attached.

#### Expected:
The login screen must be stable

### Steps to reproduce the bug

1. Deploy Paralus
2. Visit the login page and key in the email id and password.

### Are you using the latest version of the project?

You can check your version by running `helm ls|grep '^<deployment-name>'` or using [pctl](https://github.com/paralus/cli), `pctl version`, and provide the output.

```sh
NAME     	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART     	APP VERSION
myrelease	paralus  	1       	2022-10-14 19:08:59.321602061 +0530 IST	deployed	ztka-0.1.7	v0.1.6    
```

### What is your environment setup? Please tell us your cloud provider, operating system, and include the output of `kubectl version --output=yaml` and `helm version`. Any other information that you have, eg. logs and custom values, is highly appreciated!

```yaml
clientVersion:
  buildDate: "2022-05-03T13:46:05Z"
  compiler: gc
  gitCommit: 4ce5a8954017644c5420bae81d72b09b735c21f0
  gitTreeState: clean
  gitVersion: v1.24.0
  goVersion: go1.18.1
  major: "1"
  minor: "24"
  platform: linux/amd64
kustomizeVersion: v4.5.4
serverVersion:
  buildDate: "2022-08-17T18:47:37Z"
  compiler: gc
  gitCommit: 95ee5ab382d64cfe6c28967f36b53970b8374491
  gitTreeState: clean
  gitVersion: v1.24.4
  goVersion: go1.18.5
  major: "1"
  minor: "24"
  platform: linux/amd64
```

### Video

https://user-images.githubusercontent.com/10296271/196087035-0074ea74-4e5c-40ba-8d2c-f05082a638aa.mp4

- [x] I've described the bug, included steps to reproduce it, and included my environment setup with all customizations.
- [x] I'm using the latest version of the project.
