### ISSUE TITLE
Can't Modify Permissions After Setting In UI

### ISSUE THREAD

**Issue by estein9825** [paralus/dashboard#172]
### Expected vs actual behavior

After you have set permissions for a particular project in a group in the UI, you can't go back and edit it. You have to delete the permission so you have access to readd it again. This is true for organization level, project level, or namespace level. 

### Steps to reproduce the bug

1. Create a group
2. Add project permissions
3. Try to the edit the permissions, but you can't

### Are you using the latest version of the project?

You can check your version by running `helm ls|grep '^<deployment-name>'` or using [pctl](https://github.com/paralus/cli), `pctl version`, and provide the output.

```
VERSION: 0.1.0
BUILD: 0.1.0
BUILD-TIME: 1656329967
ARCH: darwin/amd64
```

### What is your environment setup? Please tell us your cloud provider, operating system, and include the output of `kubectl version --output=yaml` and `helm version`. Any other information that you have, eg. logs and custom values, is highly appreciated!
Kubectl
```
clientVersion:
  buildDate: "2022-08-23T17:44:59Z"
  compiler: gc
  gitCommit: a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2
  gitTreeState: clean
  gitVersion: v1.25.0
  goVersion: go1.19
  major: "1"
  minor: "25"
  platform: darwin/amd64
kustomizeVersion: v4.5.7
serverVersion:
  buildDate: "2022-11-29T18:41:42Z"
  compiler: gc
  gitCommit: 52e500d139bdef42fbc4540c357f0565c7867a81
  gitTreeState: clean
  gitVersion: v1.22.16-eks-ffeb93d
  goVersion: go1.16.15
  major: "1"
  minor: 22+
  platform: linux/amd64
```
Helm
```
version.BuildInfo{Version:"v3.10.3", GitCommit:"835b7334cfe2e5e27870ab3ed4135f136eecc704", GitTreeState:"clean", GoVersion:"go1.19.4"}
```

### _(optional)_ If you have ideas on why the bug happens or how it can be solved, please provide it here

Editing should work

- [X ] I've described the bug, included steps to reproduce it, and included my environment setup with all customizations.
- [X ] I'm using the latest version of the project.
